#!/usr/bin/python

import urllib.request
import json
from datetime import datetime

url = 'http://api.aladhan.com/timingsByAddress?address=Gadsden,Alabama,US&method=2'

with urllib.request.urlopen(url) as response:
    html = response.read()
    

timings = json.loads(html)['data']['timings']
del timings['Sunset']
del timings['Imsak']
del timings['Midnight']
del timings['Sunrise']

now = datetime.now().strftime('%H:%M:%S')
current_time = datetime.strptime(now, '%H:%M:%S').time()

for name, time in timings.items():
    datetimed = datetime.strptime(timings[name], "%H:%M").time()
    if current_time >= datetimed:
        current_prayer = [name, time]

    if current_time <= datetimed:
        next_prayer = [name, time]
        break

print("{0} {1}  {2} {3}".format(current_prayer[0],
                                 current_prayer[1],
                                 next_prayer[0],
                                 next_prayer[1]))
